void my_char(char);
int write(int, void*, int);
void* xmalloc(int);
void exit(int);
void my_str(char*);
void my_error(char*);
void my_int(int);
void my_num_base(int, char*);
void my_alpha();
void my_digits();
int my_strlen(char*);
int my_strindex(char*, char);
int my_strrindex(char*, char);
char* my_strdup(char*);
int my_revstr(char*);
char* my_strcpy(char*, char*);
char* my_strncpy(char*. char*, int);
int my_strcmp(char*, char*);
int my_strncmp(char*, char*, int);
char* my_strcat(char*, char*);
char* my_strconcat(char*, char*);
char* my_strnconcat(char*, char*, int);
char* my_stdstrnconcat(char*, char*, int);
char* my_strpos(char*, char);
char* my_strrpos(char*, char);
